name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # This allows the action to be triggered manually from the Actions tab.

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks out the repository so the job can access it
    - uses: actions/checkout@v2

    # Generates the snake using Platane's GitHub contribution snake action
    - uses: Platane/snk@main
      id: snake-gif
      with:
        github_user_name: lingeshsathyanarayanacm
        # These next 2 lines generate the files on a branch called "output".
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Show the status of the build (useful for debugging)
    - run: git status

    # Push the changes to the repository
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output  # Push to the 'output' branch, not master.
        force: true

    # Deploy to GitHub Pages
    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output  # The branch where the GIF and SVG files are saved
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
